model:
  propagate:
    form: "graph-conv"
    properties:
      state_dim: 20

  encode:
    form: "class-cond-bias"
    properties:
      input_dim: 20

  decode:
    form: "softmax-fcn"
    properties:
      input_dim: 20

setting:
  time_window: 14
  n_vertices: 100

training:
  optim:
    lr: 0.01
    form: "adam"
    properties:
      beta1: 0.9
      beta2: 0.99
    iters: 100

data:
  form: "simple-SIR"


device: "gpu"
