model:
  propagate:
    form: "graph-conv"
    properties:
      state_dim: 20

  encode:
    form: "class-cond-bias"
    properties:
      input_dim: 20

  decode:
    form: "softmax-fcn"
    properties:
      input_dim: 20

setting:
  time_window: 14
  n_vertices: 100
  #time_total: 50
  #seed: 0 #seed of the random number generator

training:
  optim:
    lr: 0.01
    form: "adam"
    properties:
      beta1: 0.9
      beta2: 0.99
    iters: 100

data:
  openabm:
    n_seed_infection: 10 #numer of patients zero
    fraction_SM_obs: 0.5 #fraction of Symptomatic Mild tested positive
    fraction_SS_obs: 1 #fraction of Symptomatic Severe tested positive
    initial_steps: 12 #starting time of intervention
    quarantine_HH: True #Households quarantine
    test_HH: True #Tests the households when quarantined
    adoption_fraction: 1 #app adoption (fraction)
    num_test_random: 0 #number of random tests per day
    num_test_algo: 200 #number of tests using by the ranker per day
    fp_rate: 0.0 #test false-positive rate
    fn_rate: 0.0 #test false-negative rate


device: "gpu"
